In [ ]:
#Grishma M. Jethva
#216270307051
#to create a dataframe from a dictionary and display it

import pandas as pd

people=[{"name":"Grishma",'age':18},
        {"name":"Hitarth","age":18}
       ]
print(people)
df=pd.DataFrame(people)
print(df)

In [ ]:
#Grishma M. Jethva
#216270307051
#to sort the DataFrame first by 'name' in ascending order
import pandas as pd

people=[{"name":"Grishma",'age':18},
        {"name":"Hitarth","age":18},
        {"name":"Mumtahin","age":18},
        {"name":"Heena","age":18},
        {"name":"Yash","age":18}
       ]

df=pd.DataFrame(people)
print(" data Frame\n",df)
print("\nsorting using name\n \n", df.sort_values('name'))

In [ ]:
#Grishma M. Jethva
#216270307051
#to delete the one specific column from the DataFrame
import pandas as pd


people=[{"name":"Grishma",'age':18},
        {"name":"Hitarth","age":18},
        {"name":"Mumtahin","age":18},
        {"name":"Heena","age":18},
        {"name":"Yash","age":18}
       ]

df=pd.DataFrame(people)
df1 = df.drop('age',axis=1)
print("After ddeleting age  \n\n",df1)